# mysql database configuration
spring:
  datasource:
    #    driver-class-name: com.mysql.cj.Driver
    url: jdbc:mysql://localhost:3306/insrnce-mngmnt-ptlfrm
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
